from django.db import models


class Match(models.Model):
    match_time = models.DateTimeField()
    country = models.CharField(max_length=100)
    tournament = models.CharField(max_length=100)
    home = models.CharField(max_length=100)
    away = models.CharField(max_length=100)
    h_squad_m = models.FloatField()
    a_squad_m = models.FloatField()
    squad_ratio = models.FloatField()
    score_ratio = models.CharField(max_length=2)
    conceded_ratio = models.CharField(max_length=2)
    h_lineup_m = models.FloatField(blank=True, null=True)
    a_lineup_m = models.FloatField(blank=True, null=True)
    home_score = models.IntegerField()
    away_score = models.IntegerField()
    home_pos = models.IntegerField()
    away_pos = models.IntegerField()
    home_form = models.CharField(max_length=10)
    away_form = models.CharField(max_length=10)
    h_scored = models.IntegerField()
    h_conceded = models.IntegerField()
    home_goal_difference = models.IntegerField()
    a_scored = models.IntegerField()
    a_conceded = models.IntegerField()
    away_goal_difference = models.IntegerField()
    h_played = models.IntegerField()
    a_played = models.IntegerField()
    h_team_rep = models.FloatField()
    a_team_rep = models.FloatField()
    home_rating = models.FloatField()
    away_rating = models.FloatField()
    tournament_reputation = models.IntegerField()
    reputation_tier = models.CharField(max_length=50)
    tier = models.IntegerField()
    user_count = models.IntegerField()
    match_id = models.IntegerField(primary_key=True)
    tournament_id = models.IntegerField()
    home_id = models.IntegerField()
    away_id = models.IntegerField()
    round_number = models.IntegerField()
    match_status = models.CharField(max_length=50)
    total_teams = models.IntegerField()

    class Meta:
        managed = False  # No migrations to create the table
        db_table = 'v_matches'  # Ensure Django uses the correct table name

