runtime: python312
entrypoint: gunicorn -b :$PORT betalert.wsgi

handlers:
- url: /static
  static_dir: static/

- url: /.*
  script: auto

env_variables:
  DJANGO_SETTINGS_MODULE: betalert.settings
  INSTANCE_CONNECTION_NAME: innate-empire-422116-u4:europe-west1:betalert
  DB_USER: betadmin
  DB_NAME: BetAlert
  PROJECT_ID: innate-empire-422116-u4
  PRIVATE_IP: false
