runtime: python312
entrypoint: gunicorn betalert.wsgi:application

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

beta_settings:
  cloud_sql_instances: "innate-empire-422116-u4:europe-west1:betalert"

env_variables:
  DJANGO_SETTINGS_MODULE: "betalert.settings"
  GOOGLE_CLOUD_PROJECT: "innate-empire-422116-u4"
  INSTANCE_CONNECTION_NAME: "innate-empire-422116-u4:europe-west1:betalert"

manual_scaling:
  instances: 1


